import { VerificationReportView } from "@/components/VerificationReportView";
import type { PublicReportEnvelope } from "@/lib/publicVerificationReportService";
import langgraphGuideEnvelope from "@/content/embeddedReports/langgraph-guide.v1.json";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Verify LangGraph workflows against your database — AgentSkeptic",
  description:
    "Map LangGraph-style structured tool activity to NDJSON events, run read-only SQL verification, and share a public report link.",
  robots: { index: true, follow: true },
};

const embed = langgraphGuideEnvelope as unknown as PublicReportEnvelope;
const humanText = embed.kind === "workflow" ? embed.truthReportText : embed.humanReportText;

export default function LangGraphVerificationGuidePage() {
  return (
    <main className="integrate-main">
      <h1>Verify LangGraph workflows against your database</h1>
      <p className="lede">
        LangGraph runs produce tool calls with parameters. AgentSkeptic compares that <strong>declared</strong>{" "}
        activity to <strong>observed</strong> SQLite or Postgres rows using read-only <code>SELECT</code>s—not trace
        success flags.
      </p>
      <ol className="mechanism-list">
        <li>
          Export or capture <strong>structured tool activity</strong> (JSON or NDJSON) from your graph run—the same
          shapes you would feed to Quick Verify or contract verification (see{" "}
          <Link href="/integrate">/integrate</Link>).
        </li>
        <li>
          Maintain a <strong>tools registry</strong> mapping <code>toolId</code> to SQL row checks for contract mode, or
          start with Quick Verify for inferred checks.
        </li>
        <li>
          Run <code>agentskeptic verify</code> or <code>agentskeptic quick</code> locally. To publish a
          shareable HTML report on the canonical site, pass{" "}
          <code>
            --share-report-origin https://agentskeptic.com
          </code>{" "}
          (replace with your deployment origin when self-hosting).
        </li>
        <li>
          Paste the returned <code>/r/…</code> URL in Slack, tickets, or postmortems—distribution rides on the artifact,
          not on a separate marketing workflow.
        </li>
      </ol>
      <section className="home-section" aria-labelledby="embed-heading">
        <h2 id="embed-heading">Example: green-shaped activity, missing row (ROW_ABSENT)</h2>
        <p className="muted">
          The block below is regenerated by <code>npm run generate:langgraph-guide-embed</code> from the bundled{" "}
          <code>wf_missing</code> demo so this page stays aligned with the engine.
        </p>
        <VerificationReportView humanText={humanText} payload={embed} />
      </section>
      <p className="lede">
        Normative contracts:{" "}
        <Link href="https://github.com/jwekavanagh/workflow-verifier/blob/main/docs/shareable-verification-reports.md">
          docs/shareable-verification-reports.md
        </Link>
        .
      </p>
    </main>
  );
}
