/**
 * Materializes generated buyer-truth artifacts + README marker interiors.
 * Run from repo root: `npm run codegen:buyer-truth` (cwd must be website for resolution).
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { exportBuyerFacingProjection } from "../src/lib/buyerTruth";
import { loadCommercialPlans } from "../src/lib/plans";

const here = dirname(fileURLToPath(import.meta.url));
const websiteRoot = join(here, "..");
const repoRoot = join(websiteRoot, "..");
const buyerTruthPath = join(repoRoot, "config", "buyer-truth.v1.json");

function run() {
  const catalog = loadCommercialPlans();
  const projection = exportBuyerFacingProjection(catalog);
  const snapPath = join(websiteRoot, "src", "generated", "buyerTruthProjection.snap.json");
  writeFileSync(snapPath, `${JSON.stringify(projection, null, 2)}\n`, "utf8");

  const rawBytes = readFileSync(buyerTruthPath);
  const sha = createHash("sha256").update(rawBytes).digest("hex");
  const hashPath = join(websiteRoot, "src", "generated", "buyerTruthCodegenHash.ts");
  writeFileSync(
    hashPath,
    `/** Auto-generated by codegen-buyer-truth-surfaces — do not edit. */\nexport const BUYER_TRUTH_V1_FILE_SHA256 = "${sha}" as const;\n`,
    "utf8",
  );

  const bt = JSON.parse(readFileSync(buyerTruthPath, "utf8")) as {
    readmeSegments: { commercialEntry: string[] };
  };
  const readmePath = join(repoRoot, "README.md");
  let readme = readFileSync(readmePath, "utf8");
  const interior = bt.readmeSegments.commercialEntry.join("\n\n");
  const markerRe =
    /<!-- codegen:buyer-truth:start:COMMERCIAL_ENTRY -->[\s\S]*?<!-- codegen:buyer-truth:end:COMMERCIAL_ENTRY -->/;
  if (!markerRe.test(readme)) {
    const legacyHeading = /^## Commercial CLI \(npm\) vs OSS \(this repo\)\r?\n\r?\n/;
    if (!legacyHeading.test(readme)) {
      throw new Error(
        "README.md: add COMMERCIAL_ENTRY markers or keep the legacy ## Commercial CLI (npm) vs OSS (this repo) heading + blank line for first-time bootstrap",
      );
    }
    readme = readme.replace(
      legacyHeading,
      "## Commercial CLI (npm) vs OSS (this repo)\n\n<!-- codegen:buyer-truth:start:COMMERCIAL_ENTRY -->\n<!-- codegen:buyer-truth:end:COMMERCIAL_ENTRY -->\n\n",
    );
  }
  readme = readme.replace(
    markerRe,
    `<!-- codegen:buyer-truth:start:COMMERCIAL_ENTRY -->\n${interior}\n<!-- codegen:buyer-truth:end:COMMERCIAL_ENTRY -->`,
  );
  writeFileSync(readmePath, readme, "utf8");
}

run();
