/** Stable wire codes for demo API errors (client + server). No zod/schema imports. */
export const DEMO_ERROR_CODES = {
  METHOD_NOT_ALLOWED: "DEMO_METHOD_NOT_ALLOWED",
  UNSUPPORTED_MEDIA_TYPE: "DEMO_UNSUPPORTED_MEDIA_TYPE",
  INVALID_JSON: "DEMO_INVALID_JSON",
  VALIDATION_FAILED: "DEMO_VALIDATION_FAILED",
  FIXTURES_MISSING: "DEMO_FIXTURES_MISSING",
  /** Temporary maintenance (telemetry write freeze). */
  UNAVAILABLE: "DEMO_UNAVAILABLE",
  ENGINE_FAILED: "DEMO_ENGINE_FAILED",
  RESULT_SCHEMA_MISMATCH: "DEMO_RESULT_SCHEMA_MISMATCH",
} as const;
