/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/usage/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve one verification or enforcement run (license preflight)
         * @description Called by the commercial CLI before contract verify, quick verify, or enforce. Requires Bearer API key. Body run_id must be idempotent per key.
         */
        post: operations["reserveUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commercial/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public commercial plan catalog (no secrets) */
        get: operations["getCommercialPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current usage and quota status for authenticated API key principal */
        get: operations["getCurrentUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Establish accepted enforcement baseline (baseline_missing → baseline_active only) */
        post: operations["createEnforcementBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare current material-truth projection against accepted baseline (verification attempt) */
        post: operations["checkEnforcementDrift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Procedural drift accept (action_required → rerun_required; not a verification verdict) */
        post: operations["acceptEnforcementDrift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve enforcement timeline for one workflow */
        get: operations["getEnforcementHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export governance timeline JSON for one workflow (session auth)
         * @description Returns schemaVersion 2 JSON with lifecycle, baselines, FSM transitions, verification decisions, events, and decisionEvidenceExport (manifest completeness + embedded certificate-oriented fields). This response is not equivalent to a CLI-written decision evidence bundle on disk; CLI flags --write-decision-bundle / --write-run-bundle produce the full on-disk audit file set (see /docs/decision-evidence-bundle.md in the agentskeptic repository).
         */
        get: operations["exportGovernanceAuditBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/verification-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a shareable verification report (public ingestion; size-limited; optional env disable) */
        post: operations["createPublicVerificationReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funnel/verify-outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Licensed verify-outcome beacon (idempotent per API key + run_id)
         * @description POST after a successful `POST /api/v1/usage/reserve` for the same `run_id`. Success is HTTP 204 with an empty body. Requires Bearer API key. Body `schema_version` must be 3 (`VerifyOutcomeRequestV3`). `evidence_gap_primary` duplicates `certificate.evidenceCompleteness.blockerCategory` at CLI emission time.
         */
        post: operations["postVerifyOutcomeBeacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funnel/trust-decision-blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a blocked irreversible trust decision (idempotent per API key + fingerprint)
         * @description POST when an in-process gate blocks an irreversible action. Success is HTTP 204. Requires Bearer API key with report scope. Duplicate fingerprint returns 204 without a second funnel insert.
         */
        post: operations["postTrustDecisionBlocked"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint OSS claim ticket (CLI only; product activation headers required)
         * @description Creates or returns a handoff URL for linking a verification run to a web account. Requires `X-AgentSkeptic-Cli-Product` and `X-AgentSkeptic-Cli-Version` headers (see website/src/lib/funnelProductActivationConstants.ts).
         */
        post: operations["postOssClaimTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem OSS claim ticket (browser session; optional claim_secret in body)
         * @description Requires an authenticated session; prefers pending cookie from GET /verify/link.
         */
        post: operations["postOssClaimRedeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-continuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record browser-open acknowledgement for interactive-human tickets (CLI only) */
        post: operations["postOssClaimContinuation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy handoff redirect (308 to /verify/link) */
        get: operations["getOssClaimHandoffLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnforcementEvidenceRequestV3: {
            /** @constant */
            schema_version: 3;
            run_id: string;
            workflow_id: string;
            /** @description Outcome Certificate v3 JSON (`schemaVersion` 3) including `evidenceCompleteness`, `failureSpine`, and optional `correctnessDefinition` per published schema `https://agentskeptic.com/schemas/outcome-certificate-v3.schema.json` */
            outcome_certificate: {
                [key: string]: unknown;
            };
            material_truth_sha256: string;
            certificate_sha256: string;
        };
        /** @description Hosted enforcement lifecycle response envelope for POST /check | /baselines | /accept (schema_version 2 on responses; distinct from evidence ingestion schema_version 3). */
        EnforcementFsmEnvelopeV2: {
            /** @constant */
            schema_version: 2;
            code: string;
            quota_enforced_via_reserve?: boolean;
        } & {
            [key: string]: unknown;
        };
        EnforcementAcceptEvidenceRequestV3: components["schemas"]["EnforcementEvidenceRequestV3"] & {
            /** @description Must equal expected_projection_hash_for_accept from the open drift POST /check response. */
            expected_projection_hash: string;
            /** @description Optimistic concurrency token; must match lifecycle_state_version from the prior response. */
            lifecycle_state_version: number;
        };
        EnforcementHistoryResponse: {
            /** @constant */
            schema_version: 1;
            workflow_id: string;
            events: {
                [key: string]: unknown;
            }[];
        };
        GovernanceAuditBundleV1: {
            /** @constant */
            schemaVersion: 1;
            /** Format: date-time */
            generatedAt: string;
            userId: string;
            workflowId: string;
            window?: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            baseline: {
                [key: string]: unknown;
            } | null;
            events: {
                [key: string]: unknown;
            }[];
        };
        /** @description Subset of decision-evidence-bundle-manifest-v1 validated server-side for governance export. */
        DecisionEvidenceBundleManifestHosted: {
            /** @enum {integer} */
            schemaVersion: 1;
            /** @enum {string} */
            bundleKind: "decision_evidence";
            producer: {
                name: string;
                version: string;
            };
            /** Format: date-time */
            createdAt: string;
            workflowId: string;
            completeness: {
                /** @enum {string} */
                status: "complete" | "partial" | "invalid";
                artifacts: {
                    a4Present: boolean;
                    a5Present: boolean;
                    a5Required: boolean;
                };
            };
        };
        /** @description CLI exit record files are not persisted server-side; use hosted_not_recorded for exit semantics. */
        DecisionEvidenceExportEmbeddedExitHosted: {
            /** @enum {string} */
            kind: "hosted_not_recorded";
            reason: string;
        };
        DecisionEvidenceExportEmbeddedHumanLayerFromCertificate: {
            /** @enum {string} */
            kind: "from_certificate";
            text: string;
        };
        DecisionEvidenceExportEmbeddedHumanLayerMissing: {
            /** @enum {string} */
            kind: "missing";
            reason: string;
        };
        DecisionEvidenceExportEmbedded: {
            /** @description Outcome Certificate v2 or v3 when valid; null if none. */
            outcomeCertificate: {
                [key: string]: unknown;
            } | null;
            exit: components["schemas"]["DecisionEvidenceExportEmbeddedExitHosted"];
            humanLayer: components["schemas"]["DecisionEvidenceExportEmbeddedHumanLayerFromCertificate"] | components["schemas"]["DecisionEvidenceExportEmbeddedHumanLayerMissing"];
            /** @description Not populated by current governance export (always null). */
            attestation: Record<string, never> | null;
            /** @description Not populated by current governance export (always null). */
            nextAction: Record<string, never> | null;
        };
        /** @description Certificate-oriented embed for governance JSON; not a full CLI decision bundle directory. */
        DecisionEvidenceExport: {
            manifest: components["schemas"]["DecisionEvidenceBundleManifestHosted"];
            embedded: components["schemas"]["DecisionEvidenceExportEmbedded"];
        };
        /** @description Governance timeline export (schemaVersion 2). Includes lifecycle FSM rows, verification decisions, baselines, and events. decisionEvidenceExport provides manifest completeness and certificate-oriented embeds; it is not equivalent to on-disk files from agentskeptic --write-decision-bundle. */
        GovernanceAuditBundleV2: {
            /** @constant */
            schemaVersion: 2;
            /** Format: date-time */
            generatedAt: string;
            userId: string;
            workflowId: string;
            window?: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            lifecycle?: {
                [key: string]: unknown;
            } | null;
            fsmTransitions?: {
                [key: string]: unknown;
            }[];
            verificationDecisions?: {
                [key: string]: unknown;
            }[];
            baseline: {
                [key: string]: unknown;
            } | null;
            events: {
                [key: string]: unknown;
            }[];
            decisionEvidenceExport?: components["schemas"]["DecisionEvidenceExport"];
        } & {
            [key: string]: unknown;
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance?: string;
            code?: string;
        };
        VerifyOutcomeRequestV3: {
            /** @constant */
            schema_version: 3;
            run_id: string;
            workflow_id: string;
            /** @enum {string} */
            trust_decision: "safe" | "unsafe" | "unknown";
            /**
             * @description Mirrors Outcome Certificate evidenceCompleteness.blockerCategory at CLI emission time
             * @enum {string}
             */
            evidence_gap_primary: "none" | "preview_lane" | "ingest_empty" | "ingest_unstructured" | "registry_unknown_tool" | "registry_resolution" | "database_access" | "timing_or_window" | "witness_unavailable" | "state_mismatch" | "verification_incomplete" | "event_sequence" | "control_flow_context" | "unclassified";
            reason_codes: string[];
            /** @enum {string} */
            terminal_status: "complete" | "inconsistent" | "incomplete";
            /** @enum {string} */
            workload_class: "bundled_examples" | "non_bundled";
            /** @enum {string} */
            subcommand: "batch_verify" | "quick_verify" | "verify_integrator_owned" | "activate";
            /** @description Present only when subcommand is activate (mirrors ActivationManifest-derived wire) */
            activation?: {
                [key: string]: unknown;
            } | null;
        };
        TrustDecisionRecordRequestV1: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            trust_decision: "safe" | "unsafe" | "unknown";
            /** @enum {string} */
            gate_kind: "contract_sql_irreversible" | "langgraph_checkpoint_terminal";
            routing: {
                routing_key: string;
                team?: string;
                owner_slug?: string;
            };
            certificate_snapshot: components["schemas"]["TrustCertificateSnapshotRequestV1"];
            human_blocker_lines: string[];
        };
        TrustCertificateSnapshotRequestV1: {
            /** @constant */
            schema_version: 1;
            workflow_id: string;
            /** @enum {string} */
            run_kind: "contract_sql" | "contract_sql_langgraph_checkpoint_trust" | "quick_preview";
            /** @enum {string} */
            state_relation: "matches_expectations" | "does_not_match" | "not_established";
            /** @enum {string} */
            high_stakes_reliance: "permitted" | "prohibited";
            reason_codes: string[];
            first_problem: {
                seq: number;
                tool_id: string;
                observed_trunc: string;
                expected_trunc: string;
            } | null;
        };
        /** @description v1 or v2 OSS claim ticket wire shape (see website/src/lib/ossClaimTicketPayload.ts). */
        OssClaimTicketRequest: {
            [key: string]: unknown;
        };
        OssClaimTicketHandoffResponse: {
            /** @constant */
            schema_version: 2;
            /** Format: uri */
            handoff_url: string;
        };
        OssClaimRedeemRequest: {
            claim_secret?: string;
        } & {
            [key: string]: unknown;
        };
        OssClaimRedeemOk: {
            /** @constant */
            schema_version: 1;
            run_id: string;
            terminal_status: string;
            workload_class: string;
            subcommand: string;
            build_profile: string;
            /** Format: date-time */
            claimed_at: string;
        };
        OssClaimContinuationRequest: {
            claim_secret: string;
        };
        /** @description POST accepts schemaVersion 3 only: { "schemaVersion": 3, "certificate": <OutcomeCertificateV3> } per schemas/public-verification-report-v3.schema.json. Legacy envelope POST bodies return HTTP 400. */
        PublicVerificationReportCreate: {
            [key: string]: unknown;
        };
        PublicVerificationReportCreated: {
            /** @constant */
            schemaVersion: 3;
            /** Format: uuid */
            id: string;
            /**
             * Format: uri
             * @description GET this URL to render the stored report (HTML)
             */
            url: string;
        };
        ReserveRequest: {
            run_id: string;
            /**
             * Format: date-time
             * @description ISO8601; server rejects if skew from now exceeds 300 seconds
             */
            issued_at: string;
            /**
             * @description enforce requires a paid plan (not Starter) with active subscription; verify is allowed for Starter (free included quota) and for paid plans with active subscription; overage is permitted past included for paid plans with allowOverage in plan catalog
             * @default verify
             * @enum {string}
             */
            intent: "verify" | "enforce";
        };
        ReserveAllowed: {
            /** @enum {boolean} */
            allowed: true;
            /** @enum {string} */
            plan: "starter" | "individual" | "team" | "business" | "enterprise";
            /** @description Included verifications in the current billing month (not enterprise unlimited sentinel) */
            limit: number;
            /** @description Total verifications counted this month for this API key */
            used: number;
            /** @description Same as limit for finite plans; null for enterprise unlimited */
            included_monthly: number | null;
            /** @description max(0, used - included_monthly) when the plan has a finite cap */
            overage_count: number;
        };
        ReserveError: components["schemas"]["ProblemDetails"] & {
            /** @enum {boolean} */
            allowed: false;
            /** @description Examples BAD_REQUEST, INVALID_KEY, QUOTA_EXCEEDED, ENFORCEMENT_REQUIRES_PAID_PLAN, VERIFICATION_REQUIRES_SUBSCRIPTION, SUBSCRIPTION_INACTIVE, BILLING_PRICE_UNMAPPED, INSUFFICIENT_SCOPE, KEY_EXPIRED, KEY_REVOKED, KEY_DISABLED, SERVER_ERROR */
            code: string;
            message: string;
            /**
             * Format: uri
             * @description Present for some 403 entitlement responses
             */
            upgrade_url?: string;
        };
        UsageCurrentV1: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            plan: "starter" | "individual" | "team" | "business" | "enterprise";
            year_month: string;
            /** Format: date-time */
            period_start_utc: string;
            /** Format: date-time */
            period_end_utc: string;
            used_total: number;
            included_monthly: number | null;
            allow_overage: boolean;
            overage_count: number;
            /** @enum {string} */
            quota_state: "ok" | "notice" | "warning" | "in_overage" | "at_cap";
            allowed_next: boolean;
            /** @example 24.00 */
            estimated_overage_usd: string;
        };
        CommercialPlansResponse: {
            schemaVersion: number;
            plans: {
                [key: string]: components["schemas"]["PublicPlan"];
            };
        };
        PublicPlan: {
            includedMonthly?: number | null;
            monthlyUsdCents?: number | null;
            yearlyUsdCents?: number | null;
            displayPrice?: string;
            displayPriceYearly?: string | null;
            overageMicrousdPerVerification?: number | null;
            allowOverage?: boolean;
            overageDisplayLabel?: string | null;
            marketingHeadline?: string;
            audience?: string;
            valueUnlock?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reserveUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description Allowed; quota consumed or duplicate run_id returned without double-charge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveAllowed"];
                };
            };
            /** @description Bad request (missing/invalid body, skewed issued_at) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
            /** @description Invalid API key or key lifecycle denial (revoked, disabled, expired) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
            /** @description Quota exceeded or entitlement denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
            /** @description Server error during reservation */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
        };
    };
    getCommercialPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan metadata for display and integration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommercialPlansResponse"];
                };
            };
            /** @description Plans configuration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCurrentUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current month usage and quota status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageCurrentV1"];
                };
            };
            /** @description Invalid API key or key lifecycle denial */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing required scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Plans configuration unavailable or server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createEnforcementBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnforcementEvidenceRequestV3"];
            };
        };
        responses: {
            /** @description Lifecycle transition completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementFsmEnvelopeV2"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid transition or decision-grade certificate required */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementFsmEnvelopeV2"];
                };
            };
        };
    };
    checkEnforcementDrift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnforcementEvidenceRequestV3"];
            };
        };
        responses: {
            /** @description Check completed (match, open drift, rerun pass/fail, etc.) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementFsmEnvelopeV2"];
                };
            };
            /** @description Baseline missing, remediation acknowledgement required, or other enforce guard */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementFsmEnvelopeV2"];
                };
            };
        };
    };
    acceptEnforcementDrift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnforcementAcceptEvidenceRequestV3"];
            };
        };
        responses: {
            /** @description Baseline updated; rerun POST /check required before returning to trusted-only posture */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementFsmEnvelopeV2"];
                };
            };
            /** @description Stale lifecycle version, hash pin mismatch, or invalid transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementFsmEnvelopeV2"];
                };
            };
        };
    };
    getEnforcementHistory: {
        parameters: {
            query: {
                workflow_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementHistoryResponse"];
                };
            };
        };
    };
    exportGovernanceAuditBundle: {
        parameters: {
            query: {
                workflow_id: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Governance timeline export including decisionEvidenceExport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceAuditBundleV2"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createPublicVerificationReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicVerificationReportCreate"];
            };
        };
        responses: {
            /** @description Report stored; URL is canonical origin + /r/{id} */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVerificationReportCreated"];
                };
            };
            /** @description Invalid JSON or failed schema validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Request body exceeds maximum allowed size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error storing report */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Public report ingestion disabled or server unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postVerifyOutcomeBeacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOutcomeRequestV3"];
            };
        };
        responses: {
            /** @description Beacon accepted (or duplicate ignored) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid JSON or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No reservation for this run_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Reservation too old */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postTrustDecisionBlocked: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustDecisionRecordRequestV1"];
            };
        };
        responses: {
            /** @description Record accepted or duplicate ignored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid JSON or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postOssClaimTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OssClaimTicketRequest"];
            };
        };
        responses: {
            /** @description Handoff URL returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OssClaimTicketHandoffResponse"];
                };
            };
            /** @description Ticket already claimed (idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden (unsupported CLI client) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postOssClaimRedeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OssClaimRedeemRequest"];
            };
        };
        responses: {
            /** @description Redeemed; returns run summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OssClaimRedeemOk"];
                };
            };
            /** @description Claim failed or expired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Already linked to another account */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postOssClaimContinuation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OssClaimContinuationRequest"];
            };
        };
        responses: {
            /** @description Recorded or already recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not applicable or forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getOssClaimHandoffLegacy: {
        parameters: {
            query: {
                h: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to /verify/link?h=… */
            308: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
