/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/usage/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve one verification or enforcement run (license preflight)
         * @description Called by the commercial CLI before contract verify, quick verify, or enforce. Requires Bearer API key. Body run_id must be idempotent per key.
         */
        post: operations["reserveUsage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commercial/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public commercial plan catalog (no secrets) */
        get: operations["getCommercialPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current usage and quota status for authenticated API key principal */
        get: operations["getCurrentUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or replace accepted enforcement baseline for a workflow */
        post: operations["createEnforcementBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare current run projection against accepted baseline */
        post: operations["checkEnforcementDrift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept current projection as new baseline */
        post: operations["acceptEnforcementDrift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enforcement/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve enforcement timeline for one workflow */
        get: operations["getEnforcementHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/verification-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a shareable verification report (public ingestion; size-limited; optional env disable) */
        post: operations["createPublicVerificationReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funnel/verify-outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Licensed verify-outcome beacon (idempotent per API key + run_id)
         * @description POST after a successful `POST /api/v1/usage/reserve` for the same `run_id`. Success is HTTP 204 with an empty body. Requires Bearer API key. Body schemaVersion must be 2.
         */
        post: operations["postVerifyOutcomeBeacon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funnel/trust-decision-blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a blocked irreversible trust decision (idempotent per API key + fingerprint)
         * @description POST when an in-process gate blocks an irreversible action. Success is HTTP 204. Requires Bearer API key with report scope. Duplicate fingerprint returns 204 without a second funnel insert.
         */
        post: operations["postTrustDecisionBlocked"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint OSS claim ticket (CLI only; product activation headers required)
         * @description Creates or returns a handoff URL for linking a verification run to a web account. Requires `X-AgentSkeptic-Cli-Product` and `X-AgentSkeptic-Cli-Version` headers (see website/src/lib/funnelProductActivationConstants.ts).
         */
        post: operations["postOssClaimTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem OSS claim ticket (browser session; optional claim_secret in body)
         * @description Requires an authenticated session; prefers pending cookie from GET /verify/link.
         */
        post: operations["postOssClaimRedeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-continuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record browser-open acknowledgement for interactive-human tickets (CLI only) */
        post: operations["postOssClaimContinuation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oss/claim-handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy handoff redirect (308 to /verify/link) */
        get: operations["getOssClaimHandoffLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnforcementProjectionRequest: {
            run_id: string;
            workflow_id: string;
            projection_hash: string;
            projection: {
                [key: string]: unknown;
            };
        };
        EnforcementStateResponse: {
            /** @constant */
            schema_version: 1;
            status: string;
            workflow_id: string;
        };
        EnforcementCheckResponse: components["schemas"]["EnforcementStateResponse"] & {
            expected_projection_hash: string;
            actual_projection_hash: string;
        };
        EnforcementHistoryResponse: {
            /** @constant */
            schema_version: 1;
            workflow_id: string;
            events: {
                [key: string]: unknown;
            }[];
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance?: string;
            code?: string;
        };
        VerifyOutcomeRequestV2: {
            /** @constant */
            schema_version: 2;
            run_id: string;
            workflow_id: string;
            /** @enum {string} */
            trust_decision: "safe" | "unsafe" | "unknown";
            reason_codes: string[];
            /** @enum {string} */
            terminal_status: "complete" | "inconsistent" | "incomplete";
            /** @enum {string} */
            workload_class: "bundled_examples" | "non_bundled";
            /** @enum {string} */
            subcommand: "batch_verify" | "quick_verify" | "verify_integrator_owned";
        };
        TrustDecisionRecordRequestV1: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            trust_decision: "safe" | "unsafe" | "unknown";
            /** @enum {string} */
            gate_kind: "contract_sql_irreversible" | "langgraph_checkpoint_terminal";
            routing: {
                routing_key: string;
                team?: string;
                owner_slug?: string;
            };
            certificate_snapshot: components["schemas"]["TrustCertificateSnapshotRequestV1"];
            human_blocker_lines: string[];
        };
        TrustCertificateSnapshotRequestV1: {
            /** @constant */
            schema_version: 1;
            workflow_id: string;
            /** @enum {string} */
            run_kind: "contract_sql" | "contract_sql_langgraph_checkpoint_trust" | "quick_preview";
            /** @enum {string} */
            state_relation: "matches_expectations" | "does_not_match" | "not_established";
            /** @enum {string} */
            high_stakes_reliance: "permitted" | "prohibited";
            reason_codes: string[];
            first_problem: {
                seq: number;
                tool_id: string;
                observed_trunc: string;
                expected_trunc: string;
            } | null;
        };
        /** @description v1 or v2 OSS claim ticket wire shape (see website/src/lib/ossClaimTicketPayload.ts). */
        OssClaimTicketRequest: {
            [key: string]: unknown;
        };
        OssClaimTicketHandoffResponse: {
            /** @constant */
            schema_version: 2;
            /** Format: uri */
            handoff_url: string;
        };
        OssClaimRedeemRequest: {
            claim_secret?: string;
        } & {
            [key: string]: unknown;
        };
        OssClaimRedeemOk: {
            /** @constant */
            schema_version: 1;
            run_id: string;
            terminal_status: string;
            workload_class: string;
            subcommand: string;
            build_profile: string;
            /** Format: date-time */
            claimed_at: string;
        };
        OssClaimContinuationRequest: {
            claim_secret: string;
        };
        /** @description POST accepts schemaVersion 2 only: { "schemaVersion": 2, "certificate": <OutcomeCertificateV1> } per schemas/public-verification-report-v2.schema.json. Legacy v1 envelopes are rejected with HTTP 400. */
        PublicVerificationReportCreate: {
            [key: string]: unknown;
        };
        PublicVerificationReportCreated: {
            /** @constant */
            schemaVersion: 2;
            /** Format: uuid */
            id: string;
            /**
             * Format: uri
             * @description GET this URL to render the stored report (HTML)
             */
            url: string;
        };
        ReserveRequest: {
            run_id: string;
            /**
             * Format: date-time
             * @description ISO8601; server rejects if skew from now exceeds 300 seconds
             */
            issued_at: string;
            /**
             * @description enforce requires a paid plan (not Starter) with active subscription; verify is allowed for Starter (free included quota) and for paid plans with active subscription; overage is permitted past included for paid plans with allowOverage in plan catalog
             * @default verify
             * @enum {string}
             */
            intent: "verify" | "enforce";
        };
        ReserveAllowed: {
            /** @enum {boolean} */
            allowed: true;
            /** @enum {string} */
            plan: "starter" | "individual" | "team" | "business" | "enterprise";
            /** @description Included verifications in the current billing month (not enterprise unlimited sentinel) */
            limit: number;
            /** @description Total verifications counted this month for this API key */
            used: number;
            /** @description Same as limit for finite plans; null for enterprise unlimited */
            included_monthly: number | null;
            /** @description max(0, used - included_monthly) when the plan has a finite cap */
            overage_count: number;
        };
        ReserveError: components["schemas"]["ProblemDetails"] & {
            /** @enum {boolean} */
            allowed: false;
            /** @description Examples BAD_REQUEST, INVALID_KEY, QUOTA_EXCEEDED, ENFORCEMENT_REQUIRES_PAID_PLAN, VERIFICATION_REQUIRES_SUBSCRIPTION, SUBSCRIPTION_INACTIVE, BILLING_PRICE_UNMAPPED, INSUFFICIENT_SCOPE, KEY_EXPIRED, KEY_REVOKED, KEY_DISABLED, SERVER_ERROR */
            code: string;
            message: string;
            /**
             * Format: uri
             * @description Present for some 403 entitlement responses
             */
            upgrade_url?: string;
        };
        UsageCurrentV1: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            plan: "starter" | "individual" | "team" | "business" | "enterprise";
            year_month: string;
            /** Format: date-time */
            period_start_utc: string;
            /** Format: date-time */
            period_end_utc: string;
            used_total: number;
            included_monthly: number | null;
            allow_overage: boolean;
            overage_count: number;
            /** @enum {string} */
            quota_state: "ok" | "notice" | "warning" | "in_overage" | "at_cap";
            allowed_next: boolean;
            /** @example 24.00 */
            estimated_overage_usd: string;
        };
        CommercialPlansResponse: {
            schemaVersion: number;
            plans: {
                [key: string]: components["schemas"]["PublicPlan"];
            };
        };
        PublicPlan: {
            includedMonthly?: number | null;
            monthlyUsdCents?: number | null;
            yearlyUsdCents?: number | null;
            displayPrice?: string;
            displayPriceYearly?: string | null;
            overageMicrousdPerVerification?: number | null;
            allowOverage?: boolean;
            overageDisplayLabel?: string | null;
            marketingHeadline?: string;
            audience?: string;
            valueUnlock?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reserveUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description Allowed; quota consumed or duplicate run_id returned without double-charge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveAllowed"];
                };
            };
            /** @description Bad request (missing/invalid body, skewed issued_at) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
            /** @description Invalid API key or key lifecycle denial (revoked, disabled, expired) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
            /** @description Quota exceeded or entitlement denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
            /** @description Server error during reservation */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveError"];
                };
            };
        };
    };
    getCommercialPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan metadata for display and integration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommercialPlansResponse"];
                };
            };
            /** @description Plans configuration unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCurrentUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current month usage and quota status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageCurrentV1"];
                };
            };
            /** @description Invalid API key or key lifecycle denial */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing required scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Plans configuration unavailable or server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createEnforcementBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnforcementProjectionRequest"];
            };
        };
        responses: {
            /** @description Baseline created or replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementStateResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    checkEnforcementDrift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnforcementProjectionRequest"];
            };
        };
        responses: {
            /** @description Comparison result (ok or drift) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementCheckResponse"];
                };
            };
            /** @description Baseline not initialized */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    acceptEnforcementDrift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnforcementProjectionRequest"];
            };
        };
        responses: {
            /** @description Drift accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementStateResponse"];
                };
            };
        };
    };
    getEnforcementHistory: {
        parameters: {
            query: {
                workflow_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnforcementHistoryResponse"];
                };
            };
        };
    };
    createPublicVerificationReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicVerificationReportCreate"];
            };
        };
        responses: {
            /** @description Report stored; URL is canonical origin + /r/{id} */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVerificationReportCreated"];
                };
            };
            /** @description Invalid JSON or failed schema validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Request body exceeds maximum allowed size */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error storing report */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Public report ingestion disabled or server unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postVerifyOutcomeBeacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOutcomeRequestV2"];
            };
        };
        responses: {
            /** @description Beacon accepted (or duplicate ignored) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid JSON or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No reservation for this run_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Reservation too old */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postTrustDecisionBlocked: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustDecisionRecordRequestV1"];
            };
        };
        responses: {
            /** @description Record accepted or duplicate ignored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid JSON or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postOssClaimTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OssClaimTicketRequest"];
            };
        };
        responses: {
            /** @description Handoff URL returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OssClaimTicketHandoffResponse"];
                };
            };
            /** @description Ticket already claimed (idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden (unsupported CLI client) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postOssClaimRedeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OssClaimRedeemRequest"];
            };
        };
        responses: {
            /** @description Redeemed; returns run summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OssClaimRedeemOk"];
                };
            };
            /** @description Claim failed or expired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Already linked to another account */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    postOssClaimContinuation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OssClaimContinuationRequest"];
            };
        };
        responses: {
            /** @description Recorded or already recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not applicable or forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Server error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getOssClaimHandoffLegacy: {
        parameters: {
            query: {
                h: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to /verify/link?h=… */
            308: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
