/** Canonical machine codes for bundle signature verification and signing failures. */

export const BUNDLE_SIGNATURE_UNSIGNED_MANIFEST = "BUNDLE_SIGNATURE_UNSIGNED_MANIFEST";
export const BUNDLE_SIGNATURE_MANIFEST_UNSUPPORTED_VERSION =
  "BUNDLE_SIGNATURE_MANIFEST_UNSUPPORTED_VERSION";
export const BUNDLE_SIGNATURE_MANIFEST_INVALID = "BUNDLE_SIGNATURE_MANIFEST_INVALID";
export const BUNDLE_SIGNATURE_MISSING_ARTIFACT = "BUNDLE_SIGNATURE_MISSING_ARTIFACT";
export const BUNDLE_SIGNATURE_ARTIFACT_INTEGRITY = "BUNDLE_SIGNATURE_ARTIFACT_INTEGRITY";
export const BUNDLE_SIGNATURE_SIDECAR_INVALID = "BUNDLE_SIGNATURE_SIDECAR_INVALID";
export const BUNDLE_SIGNATURE_SIGNED_HASH_MISMATCH = "BUNDLE_SIGNATURE_SIGNED_HASH_MISMATCH";
export const BUNDLE_SIGNATURE_PUBLIC_KEY_MISMATCH = "BUNDLE_SIGNATURE_PUBLIC_KEY_MISMATCH";
export const BUNDLE_SIGNATURE_CRYPTO_INVALID = "BUNDLE_SIGNATURE_CRYPTO_INVALID";
export const BUNDLE_SIGNATURE_PRIVATE_KEY_INVALID = "BUNDLE_SIGNATURE_PRIVATE_KEY_INVALID";

export type BundleSignatureCode =
  | typeof BUNDLE_SIGNATURE_UNSIGNED_MANIFEST
  | typeof BUNDLE_SIGNATURE_MANIFEST_UNSUPPORTED_VERSION
  | typeof BUNDLE_SIGNATURE_MANIFEST_INVALID
  | typeof BUNDLE_SIGNATURE_MISSING_ARTIFACT
  | typeof BUNDLE_SIGNATURE_ARTIFACT_INTEGRITY
  | typeof BUNDLE_SIGNATURE_SIDECAR_INVALID
  | typeof BUNDLE_SIGNATURE_SIGNED_HASH_MISMATCH
  | typeof BUNDLE_SIGNATURE_PUBLIC_KEY_MISMATCH
  | typeof BUNDLE_SIGNATURE_CRYPTO_INVALID
  | typeof BUNDLE_SIGNATURE_PRIVATE_KEY_INVALID;
