import { CLI_OPERATIONAL_CODES, type OperationalCode } from "./cliOperationalCodes.js";
import type { FailureOrigin } from "./failureOriginTypes.js";
import {
  COMPARE_INPUT_RUN_LEVEL_INCONSISTENT_MESSAGE,
  WORKFLOW_RESULT_RUN_LEVEL_CODES_MISMATCH_MESSAGE,
} from "./runLevelDriftMessages.js";
import type {
  ActionableFailureCategory,
  ActionableFailureSeverity,
  RecommendedActionCode,
} from "./types.js";

export type OperationalDispositionRow = {
  origin: FailureOrigin;
  summary: string;
  actionableCategory: ActionableFailureCategory;
  actionableSeverity: ActionableFailureSeverity;
  recommendedAction: RecommendedActionCode;
  automationSafe: boolean;
};

/**
 * Sole source of operational diagnosis values (origin, summary, actionable category/severity,
 * recommendedAction, automationSafe).
 * Catalog and actionableFailure derive exported maps from this object only.
 */
export const OPERATIONAL_DISPOSITION = {
  [CLI_OPERATIONAL_CODES.CLI_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete CLI arguments for agentskeptic.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.REGISTRY_READ_FAILED]: {
    origin: "inputs",
    summary: "Tools registry file could not be read.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.REGISTRY_JSON_SYNTAX]: {
    origin: "inputs",
    summary: "Tools registry JSON could not be parsed.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.REGISTRY_SCHEMA_INVALID]: {
    origin: "inputs",
    summary: "Tools registry failed schema validation.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.REGISTRY_DUPLICATE_TOOL_ID]: {
    origin: "inputs",
    summary: "Tools registry contains duplicate toolId entries.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EVENTS_READ_FAILED]: {
    origin: "inputs",
    summary: "Events file could not be read.",
    actionableCategory: "bad_input",
    actionableSeverity: "high",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.SQLITE_DATABASE_OPEN_FAILED]: {
    origin: "downstream_system_state",
    summary: "SQLite verification database could not be opened.",
    actionableCategory: "downstream_execution_failure",
    actionableSeverity: "high",
    recommendedAction: "fix_verification_database_connection",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.POSTGRES_CLIENT_SETUP_FAILED]: {
    origin: "downstream_system_state",
    summary: "Postgres verification client could not be established.",
    actionableCategory: "downstream_execution_failure",
    actionableSeverity: "high",
    recommendedAction: "fix_verification_database_connection",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.WORKFLOW_RESULT_SCHEMA_INVALID]: {
    origin: "workflow_flow",
    summary: "Emitted workflow result failed JSON schema validation.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_saved_workflow_json",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.INTERNAL_ERROR]: {
    origin: "workflow_flow",
    summary: "Unexpected internal error in agentskeptic.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_USAGE]: {
    origin: "workflow_flow",
    summary: "Invalid or incomplete arguments for agentskeptic compare.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_INSUFFICIENT_RUNS]: {
    origin: "workflow_flow",
    summary: "compare requires at least two WorkflowResult inputs.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_WORKFLOW_ID_MISMATCH]: {
    origin: "workflow_flow",
    summary: "Compared WorkflowResult files use different workflowId values.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_compare_workflow_inputs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_INPUT_READ_FAILED]: {
    origin: "inputs",
    summary: "A compare input file could not be read.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_INPUT_JSON_SYNTAX]: {
    origin: "inputs",
    summary: "A compare input file is not valid JSON.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_INPUT_SCHEMA_INVALID]: {
    origin: "inputs",
    summary: "A compare input file failed WorkflowResult schema validation.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_WORKFLOW_TRUTH_MISMATCH]: {
    origin: "workflow_flow",
    summary: "Saved workflowTruthReport does not match recomputation from engine fields.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_saved_workflow_json",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_RUN_COMPARISON_REPORT_INVALID]: {
    origin: "workflow_flow",
    summary: "Run comparison report failed schema validation.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_compare_workflow_inputs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_MANIFEST_READ_FAILED]: {
    origin: "inputs",
    summary: "Compare manifest file could not be read.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_MANIFEST_SCHEMA_INVALID]: {
    origin: "inputs",
    summary: "Compare manifest failed schema validation or certificate profile invariants.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_RESOLVE_PATH_FAILED]: {
    origin: "inputs",
    summary: "Compare manifest resolved a workflow or events path that does not exist.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_EVENTS_LOAD_FAILED]: {
    origin: "inputs",
    summary: "Events NDJSON for compare could not be loaded for a run.",
    actionableCategory: "bad_input",
    actionableSeverity: "high",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_REGRESSION_ARTIFACT_INVALID]: {
    origin: "workflow_flow",
    summary: "Regression artifact failed schema validation (internal).",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_CERTIFICATE_BUILD_FAILED]: {
    origin: "workflow_flow",
    summary: "Outcome certificate could not be built for a compared run.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_compare_workflow_inputs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.VERIFICATION_POLICY_INVALID]: {
    origin: "inputs",
    summary: "Verification policy arguments are invalid.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EVENTUAL_MODE_NOT_SUPPORTED_IN_PROCESS_HOOK]: {
    origin: "workflow_flow",
    summary: "In-process verification does not support eventual consistency; use batch verifyWorkflow.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_verification_policy_and_hook",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.VALIDATE_REGISTRY_USAGE]: {
    origin: "workflow_flow",
    summary: "Invalid or incomplete arguments for validate-registry.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EXECUTION_TRACE_USAGE]: {
    origin: "workflow_flow",
    summary: "Invalid or incomplete arguments for execution-trace.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.TRACE_DUPLICATE_RUN_EVENT_ID]: {
    origin: "workflow_flow",
    summary: "Duplicate runEventId in execution trace input.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_execution_trace_structure",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.TRACE_UNKNOWN_PARENT_RUN_EVENT_ID]: {
    origin: "workflow_flow",
    summary: "parentRunEventId does not reference a prior event.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_execution_trace_structure",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.TRACE_PARENT_FORWARD_REFERENCE]: {
    origin: "workflow_flow",
    summary: "parentRunEventId references an event that is not strictly earlier.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_execution_trace_structure",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.COMPARE_INPUT_RUN_LEVEL_INCONSISTENT]: {
    origin: "workflow_flow",
    summary: COMPARE_INPUT_RUN_LEVEL_INCONSISTENT_MESSAGE,
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_compare_workflow_inputs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.WORKFLOW_RESULT_RUN_LEVEL_CODES_MISMATCH]: {
    origin: "workflow_flow",
    summary: WORKFLOW_RESULT_RUN_LEVEL_CODES_MISMATCH_MESSAGE,
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_saved_workflow_json",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_TRANSITION_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete arguments for agentskeptic plan-transition.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_plan_transition_cli_and_refs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_TRANSITION_GIT_TOO_OLD]: {
    origin: "downstream_system_state",
    summary: "Git version is below the minimum required for plan-transition (2.30.0).",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "upgrade_git_or_retry_git",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_TRANSITION_GIT_FAILED]: {
    origin: "downstream_system_state",
    summary: "Git command failed during plan-transition.",
    actionableCategory: "downstream_execution_failure",
    actionableSeverity: "high",
    recommendedAction: "upgrade_git_or_retry_git",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_TRANSITION_BAD_REF]: {
    origin: "inputs",
    summary: "Before or After ref could not be resolved to a commit.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_transition_cli_and_refs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_TRANSITION_GIT_PARSE]: {
    origin: "workflow_flow",
    summary: "git diff -z --name-status output could not be parsed.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_VALIDATION_NO_FRONT_MATTER]: {
    origin: "inputs",
    summary: "Plan.md is missing valid YAML front matter.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_VALIDATION_YAML_INVALID]: {
    origin: "inputs",
    summary:
      "YAML parse failed in Plan.md (YAML front matter or the body section \"Repository transition validation\").",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_VALIDATION_SCHEMA_INVALID]: {
    origin: "inputs",
    summary:
      "planValidation rules failed JSON Schema validation (front matter key planValidation or body yaml fence under \"Repository transition validation\").",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_VALIDATION_INSUFFICIENT_SPEC]: {
    origin: "inputs",
    summary:
      "Plan.md has no machine-checkable transition rules: add planValidation to YAML front matter; or add a single ## Repository transition validation section whose first fenced block is yaml/yml; or cite qualifying repo-relative paths in the plan body or todos so derived rules can require those paths to appear in the git diff (see docs — derived citations).",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_VALIDATION_AMBIGUOUS_BODY_RULES]: {
    origin: "inputs",
    summary:
      "Plan.md body has duplicate \"Repository transition validation\" headings or multiple yaml/yml fences in that section.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_VALIDATION_INVALID_PATTERN]: {
    origin: "inputs",
    summary: "A glob pattern in planValidation.rules is invalid or unsafe.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_document_and_patterns",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.PLAN_PATH_OUTSIDE_REPO]: {
    origin: "inputs",
    summary: "--plan must resolve to a path inside --repo.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_plan_transition_cli_and_refs",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ENFORCE_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete arguments for agentskeptic enforce.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.CI_LOCK_SCHEMA_INVALID]: {
    origin: "inputs",
    summary: "CI lock file is not valid JSON or does not match ci-lock-v1 schema.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_saved_workflow_json",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.VERIFICATION_OUTPUT_LOCK_MISMATCH]: {
    origin: "workflow_flow",
    summary: "CI enforcement lock did not match expected fixture.",
    actionableCategory: "state_inconsistency",
    actionableSeverity: "high",
    recommendedAction: "fix_saved_workflow_json",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete arguments for agentskeptic assurance.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_MANIFEST_READ_FAILED]: {
    origin: "inputs",
    summary: "Assurance manifest file could not be read.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_MANIFEST_JSON_SYNTAX]: {
    origin: "inputs",
    summary: "Assurance manifest JSON could not be parsed.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_MANIFEST_SCHEMA_INVALID]: {
    origin: "inputs",
    summary: "Assurance manifest failed schema validation.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_REPO_ROOT_NOT_FOUND]: {
    origin: "workflow_flow",
    summary: "Could not locate agentskeptic package root from the manifest path.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_CLI_MISSING]: {
    origin: "workflow_flow",
    summary: "Built dist/cli.js was not found; run npm run build.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_MANIFEST_PATH_MISSING]: {
    origin: "inputs",
    summary: "A path referenced by the assurance manifest does not exist.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_REPORT_READ_FAILED]: {
    origin: "inputs",
    summary: "Assurance run report file could not be read.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_REPORT_JSON_SYNTAX]: {
    origin: "inputs",
    summary: "Assurance run report JSON could not be parsed.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_REPORT_SCHEMA_INVALID]: {
    origin: "inputs",
    summary: "Assurance run report failed schema validation.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_REPORT_ISSUED_AT_FUTURE_SKEW]: {
    origin: "inputs",
    summary: "Assurance report issuedAt is too far in the future relative to the runner clock.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ASSURANCE_STALE_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete arguments for agentskeptic assurance stale.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.LICENSE_KEY_MISSING]: {
    origin: "inputs",
    summary: "Commercial agentskeptic requires AGENTSKEPTIC_API_KEY for contract verification (legacy WORKFLOW_VERIFIER_API_KEY accepted).",
    actionableCategory: "bad_input",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.LICENSE_DENIED]: {
    origin: "workflow_flow",
    summary: "License or quota check denied this contract verification run.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.LICENSE_USAGE_UNAVAILABLE]: {
    origin: "downstream_system_state",
    summary: "License service was unreachable after retries.",
    actionableCategory: "downstream_execution_failure",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ENFORCEMENT_REQUIRES_PAID_PLAN]: {
    origin: "workflow_flow",
    summary:
      "Enforcement (CI gate) requires a paid plan with an active subscription.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.VERIFICATION_REQUIRES_SUBSCRIPTION]: {
    origin: "workflow_flow",
    summary:
      "Licensed verification with the commercial CLI requires an active subscription; subscribe or use an OSS build for local verify.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.ENFORCE_REQUIRES_COMMERCIAL_BUILD]: {
    origin: "workflow_flow",
    summary:
      "CI enforcement (enforce) and CI lock flags are not available in the OSS build; use the published agentskeptic npm package or a commercial local build with a license API.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.SHARE_REPORT_FAILED]: {
    origin: "downstream_system_state",
    summary: "Publishing the verification report to the configured origin failed after verification succeeded.",
    actionableCategory: "downstream_execution_failure",
    actionableSeverity: "medium",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete CLI arguments for agentskeptic bootstrap.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_INPUT_INVALID]: {
    origin: "inputs",
    summary: "Bootstrap pack input JSON failed validation or semantic checks.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_OUT_EXISTS]: {
    origin: "inputs",
    summary: "Bootstrap --out path already exists; remove it or choose a new directory.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_NO_TOOL_CALLS]: {
    origin: "inputs",
    summary: "Bootstrap input contained no tool_calls to synthesize.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_TOOL_CALL_ARGUMENTS_INVALID]: {
    origin: "inputs",
    summary: "A tool_calls[].function.arguments string was not valid JSON object text.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_registry_events_or_compare_files",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_QUICK_NOT_PASS]: {
    origin: "inputs",
    summary: "Quick Verify did not return verdict pass for the synthesized bootstrap input.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.BOOTSTRAP_NO_EXPORTABLE_TOOLS]: {
    origin: "inputs",
    summary: "Quick Verify produced no exportable registry tools for contract replay.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.CROSSING_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete CLI arguments for agentskeptic crossing.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.LANGGRAPH_CHECKPOINT_TRUST_GENERIC_MODE_CONFLICT]: {
    origin: "inputs",
    summary:
      "Generic contract verify was invoked without --langgraph-checkpoint-trust while the events file contains schemaVersion 3 tool_observed lines for the workflow.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EMIT_WORKFLOW_ID_INVALID]: {
    origin: "inputs",
    summary: "Emitter initialization failed because workflowId is missing or blank.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EMIT_TOOL_ID_INVALID]: {
    origin: "inputs",
    summary: "Emitter input failed because toolId is missing or blank.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EMIT_RETRIEVAL_SOURCE_INVALID]: {
    origin: "inputs",
    summary: "Emitter retrieval input failed because source is missing or blank.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EMIT_LANGGRAPH_CHECKPOINT_INVALID]: {
    origin: "inputs",
    summary: "Emitter LangGraph checkpoint fields are incomplete or invalid.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EMIT_LINT_USAGE]: {
    origin: "inputs",
    summary: "Invalid or incomplete arguments for agentskeptic emit-lint.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EMIT_LINT_FAILED]: {
    origin: "workflow_flow",
    summary: "Emit lint failed due to malformed or inconsistent run-event stream.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "medium",
    recommendedAction: "fix_event_ingest_and_steps",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.RECEIPT_SCHEMA_INVALID]: {
    origin: "workflow_flow",
    summary: "Verification receipt document failed schema validation.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.RECEIPT_PERSIST_FAILED]: {
    origin: "downstream_system_state",
    summary: "Could not write verification receipt to disk.",
    actionableCategory: "control_flow_problem",
    actionableSeverity: "high",
    recommendedAction: "manual_review",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EXECUTION_IDENTITY_MISMATCH]: {
    origin: "inputs",
    summary: "Packaged execution-identity differs from pinned expected JSON.",
    actionableCategory: "bad_input",
    actionableSeverity: "medium",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
  [CLI_OPERATIONAL_CODES.EXECUTION_IDENTITY_USAGE]: {
    origin: "inputs",
    summary: "Invalid arguments for agentskeptic execution-identity verify.",
    actionableCategory: "bad_input",
    actionableSeverity: "low",
    recommendedAction: "fix_cli_usage",
    automationSafe: false,
  },
} as const satisfies Record<OperationalCode, OperationalDispositionRow>;
