// Generated by npm run emit-primary-marketing — do not hand edit.

export const PUBLIC_DISTRIBUTION_SSOT_BLOB_URL = "https://github.com/jwekavanagh/agentskeptic/blob/main/docs/public-distribution.md";

export const PUBLIC_CANONICAL_SITE_ORIGIN = "https://agentskeptic.com";

export const AGENTSKEPTIC_CLI_SEMVER = "1.1.0";

export function formatDistributionFooter(): string {
  return "Context: https://agentskeptic.com/database-truth-vs-traces\n"
    + "https://agentskeptic.com/integrate\n"
    + "https://agentskeptic.com/\n"
    + "Distribution contract (SSOT): https://github.com/jwekavanagh/agentskeptic/blob/main/docs/public-distribution.md\n";
}
