// Generated by npm run sync:public-product-anchors — do not hand edit.

export const PUBLIC_DISTRIBUTION_SSOT_BLOB_URL = "https://github.com/jwekavanagh/workflow-verifier/blob/main/docs/public-distribution-ssot.md";

export function formatDistributionFooter(): string {
  return "Distribution contract (SSOT): " + PUBLIC_DISTRIBUTION_SSOT_BLOB_URL + "\n";
}
