/**
 * Sole definition of emitted step / resolver `reason.code` and registry validation resolution codes.
 * Pair with wireReasonEmittersGuard.test.ts (six emitter files only).
 */

/** Resolver / registry parameter resolution failures (`{ ok: false }` from resolveVerificationRequest). */
export const REGISTRY_RESOLVER_CODE = {
  CONST_STRING_EMPTY: "CONST_STRING_EMPTY",
  STRING_SPEC_POINTER_MISSING: "STRING_SPEC_POINTER_MISSING",
  STRING_SPEC_TYPE: "STRING_SPEC_TYPE",
  STRING_SPEC_EMPTY: "STRING_SPEC_EMPTY",
  KEY_VALUE_POINTER_MISSING: "KEY_VALUE_POINTER_MISSING",
  KEY_VALUE_NOT_SCALAR: "KEY_VALUE_NOT_SCALAR",
  KEY_VALUE_SPEC_INVALID: "KEY_VALUE_SPEC_INVALID",
  TABLE_POINTER_INVALID: "TABLE_POINTER_INVALID",
  TABLE_SPEC_INVALID: "TABLE_SPEC_INVALID",
  INVALID_IDENTIFIER: "INVALID_IDENTIFIER",
  REQUIRED_FIELDS_POINTER_MISSING: "REQUIRED_FIELDS_POINTER_MISSING",
  REQUIRED_FIELDS_NOT_OBJECT: "REQUIRED_FIELDS_NOT_OBJECT",
  REQUIRED_FIELDS_VALUE_UNDEFINED: "REQUIRED_FIELDS_VALUE_UNDEFINED",
  REQUIRED_FIELDS_VALUE_NOT_SCALAR: "REQUIRED_FIELDS_VALUE_NOT_SCALAR",
  UNSUPPORTED_VERIFICATION_KIND: "UNSUPPORTED_VERIFICATION_KIND",
  DUPLICATE_EFFECT_ID: "DUPLICATE_EFFECT_ID",
  RELATIONAL_EXPECT_VALUE_INVALID: "RELATIONAL_EXPECT_VALUE_INVALID",
  RELATIONAL_SUM_COLUMN_REQUIRED: "RELATIONAL_SUM_COLUMN_REQUIRED",
  EQUALITY_DUPLICATE_COLUMN: "EQUALITY_DUPLICATE_COLUMN",
  FILTER_EQ_OVERLAPS_IDENTITY: "FILTER_EQ_OVERLAPS_IDENTITY",
  RELATIONAL_UNSUPPORTED_DIALECT: "RELATIONAL_UNSUPPORTED_DIALECT",
} as const;

/** SQL reconciliation / policy / pipeline step `reasons[].code` values (post-resolution verification axis). */
export const SQL_VERIFICATION_OUTCOME_CODE = {
  ROW_ABSENT: "ROW_ABSENT",
  DUPLICATE_ROWS: "DUPLICATE_ROWS",
  ROW_SHAPE_MISMATCH: "ROW_SHAPE_MISMATCH",
  UNREADABLE_VALUE: "UNREADABLE_VALUE",
  VALUE_MISMATCH: "VALUE_MISMATCH",
  CONNECTOR_ERROR: "CONNECTOR_ERROR",
  MULTI_EFFECT_INCOMPLETE: "MULTI_EFFECT_INCOMPLETE",
  MULTI_EFFECT_ALL_FAILED: "MULTI_EFFECT_ALL_FAILED",
  MULTI_EFFECT_PARTIAL: "MULTI_EFFECT_PARTIAL",
  ROW_NOT_OBSERVED_WITHIN_WINDOW: "ROW_NOT_OBSERVED_WITHIN_WINDOW",
  MULTI_EFFECT_UNCERTAIN_WITHIN_WINDOW: "MULTI_EFFECT_UNCERTAIN_WITHIN_WINDOW",
  UNKNOWN_TOOL: "UNKNOWN_TOOL",
  RETRY_OBSERVATIONS_DIVERGE: "RETRY_OBSERVATIONS_DIVERGE",
  RELATED_ROWS_ABSENT: "RELATED_ROWS_ABSENT",
  RELATIONAL_EXPECTATION_MISMATCH: "RELATIONAL_EXPECTATION_MISMATCH",
  RELATIONAL_SCALAR_UNUSABLE: "RELATIONAL_SCALAR_UNUSABLE",
  ROW_PRESENT_WHEN_FORBIDDEN: "ROW_PRESENT_WHEN_FORBIDDEN",
  ORPHAN_ROW_DETECTED: "ORPHAN_ROW_DETECTED",
  FORBIDDEN_ROWS_STILL_PRESENT_WITHIN_WINDOW: "FORBIDDEN_ROWS_STILL_PRESENT_WITHIN_WINDOW",
  STATE_WITNESS_UNAVAILABLE_IN_SQLITE_FILE_MODE: "STATE_WITNESS_UNAVAILABLE_IN_SQLITE_FILE_MODE",
  STATE_WITNESS_SETUP_ERROR: "STATE_WITNESS_SETUP_ERROR",
  VECTOR_NOT_FOUND: "VECTOR_NOT_FOUND",
  VECTOR_METADATA_MISMATCH: "VECTOR_METADATA_MISMATCH",
  VECTOR_PAYLOAD_MISMATCH: "VECTOR_PAYLOAD_MISMATCH",
  VECTOR_PROVIDER_ERROR: "VECTOR_PROVIDER_ERROR",
  OBJECT_MISSING: "OBJECT_MISSING",
  OBJECT_DIGEST_MISMATCH: "OBJECT_DIGEST_MISMATCH",
  OBJECT_SIZE_MISMATCH: "OBJECT_SIZE_MISMATCH",
  OBJECT_METADATA_MISMATCH: "OBJECT_METADATA_MISMATCH",
  OBJECT_TOO_LARGE_FOR_HASH: "OBJECT_TOO_LARGE_FOR_HASH",
  HTTP_WITNESS_STATUS_MISMATCH: "HTTP_WITNESS_STATUS_MISMATCH",
  HTTP_WITNESS_ASSERTION_MISMATCH: "HTTP_WITNESS_ASSERTION_MISMATCH",
  HTTP_WITNESS_NETWORK_ERROR: "HTTP_WITNESS_NETWORK_ERROR",
  MONGO_DOCUMENT_MISSING: "MONGO_DOCUMENT_MISSING",
  MONGO_VALUE_MISMATCH: "MONGO_VALUE_MISMATCH",
  RELATIONAL_UNSUPPORTED_DIALECT: "RELATIONAL_UNSUPPORTED_DIALECT",
  BOUNDED_WINDOW_EXPIRED_WITHOUT_OBSERVATION: "BOUNDED_WINDOW_EXPIRED_WITHOUT_OBSERVATION",
  BOUNDED_MODE_UNSUPPORTED_FOR_CONNECTOR: "BOUNDED_MODE_UNSUPPORTED_FOR_CONNECTOR",
  CONNECTOR_UNSUPPORTED_IN_SCOPE: "CONNECTOR_UNSUPPORTED_IN_SCOPE",
} as const;

export const UNKNOWN_TOOL = SQL_VERIFICATION_OUTCOME_CODE.UNKNOWN_TOOL;

/** Fixed `code` strings on registry validation resolutionIssues / resolutionSkipped. */
export const REGISTRY_VALIDATION_CODE = {
  NO_STEPS_FOR_WORKFLOW: "NO_STEPS_FOR_WORKFLOW",
  RETRY_OBSERVATIONS_DIVERGE: "RETRY_OBSERVATIONS_DIVERGE",
  UNKNOWN_TOOL: "UNKNOWN_TOOL",
} as const;
